#ifndef STEREO_IR_HLS_CONFIG_H
#define STEREO_IR_HLS_CONFIG_H

#define STEREO_MAX_WIDTH  1224
#define STEREO_MAX_HEIGHT 1024
#define STEREO_DEFAULT_WIDTH  1224
#define STEREO_DEFAULT_HEIGHT 1024
#define STEREO_DEFAULT_DEPTH_MM 1000
#define STEREO_Q16_SHIFT 16
#define STEREO_Q16_ONE (1 << STEREO_Q16_SHIFT)

#endif

